### PR TITLE
Create testing-case.py

### PR DESCRIPTION
**Pull request by DEVOPS-CAREER**
please review the file and let me know

### CODE REVIEW

**Review by mydevops-2022 — COMMENTED** [review]
O boy , you did very well. I authorize you to go ahead and merge.
good job

**Comment by mydevops-2022** [comment]
Go ahead and merge!

**Comment by DEVOPS-CAREER** [comment]
> Go ahead and merge!

Thanks

**Comment by DEVOPS-CAREER** [comment]
hello

**Review by mydevops-2022 — APPROVED** [review]
good

**Comment by mydevops-2022** [comment]
this looks awesome, go ahead and merge .

**Pull request merged**
